import turtle

screen = turtle.Screen()
screen.bgcolor('green')

t=turtle.Turtle()

t.penup()
t.goto(0,200)
t.pendown()
t.write("All About Me", font=("Arial", 45, "bold"), align="center")
t.penup()
t.goto(0,-50)
t.pendown()
t.write("Laila Hockenberry", font=("Arial", 40, "bold"), align="center")
t.penup()
t.goto(0,-300)
t.pendown()
t.pensize(5)
t.pencolor('powder blue')
t.fillcolor('powder blue')
t.begin_fill()
t.circle(87)
t.end_fill()
t2=turtle.Turtle()
t2.penup()
turtle.addshape("taco.gif")
t2.shape("taco.gif")
t2.goto(100,100)
a=t2.stamp()

t2.penup()
turtle.addshape("pasta.gif")
t2.shape("pasta.gif")
t2.goto(-100,100)
a=t2.stamp()
enter=input("Press enter to begin")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('purple')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Foods", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(-160,40)
t.write("Tacos", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(0,40)
t.write("Pasta", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(140,40)
t.write("Grape Leaves", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(-75, 105)
t.fillcolor('blue')
t.pendown()
t.begin_fill()
t.forward(150)
t.left(90)
t.forward(100)
t.left(90)
t.forward(150)
t.left(90)
t.forward(100)
t.end_fill()

t2.penup()
turtle.addshape("taco.gif")
t2.shape("taco.gif")
t2.goto(100,-100)
a=t2.stamp()

t2.penup()
t2.goto(-100,-100)
turtle.addshape("pasta.gif")
t2.shape("pasta.gif")
t2.goto(-100,-100)
a=t2.stamp()
t2.goto(-100,-200)


enter=input("Press enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('powder blue')
t.pencolor('black')
t.penup()
t.goto(0,200)
t.pendown()
t.write("Hobbies", font=("Arial", 35, "bold"), align="center")
t.penup()
t.penup()
t.goto(-250,40)
t.write("Running", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(-150,40)
t.write("Acting", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(-40,40)
t.write("Singing", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(140,40)
t.write("Eating", font=("Arial", 15, "bold"), align="center")
t.penup()
t.pencolor('pink')
t.fillcolor('black')
t.begin_fill()
t.goto(-50,-10)
t.pendown()
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.end_fill()
t2.penup()
turtle.addshape("running.gif")
t2.shape("running.gif")
t2.goto(100,-200)
a=t2.stamp()


t2.penup()
turtle.addshape("acting.gif")
t2.shape("acting.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)

enter=input("Press enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('chocolate')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Movie", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(-10,100)
t.pencolor('blue')
t.fillcolor('blue')
t.penup()
t.goto(-10,100)
t.pencolor('black')
t.fillcolor('beige')
t.pendown()
t.begin_fill()
t.circle(30,180)
t.end_fill()
t.penup()
t.goto(0,-50)
t.pendown()
t.pencolor("black")
t.write("Wonder", font=("Arial", 30, "bold"), align="center")

t2.penup()
turtle.addshape("wonder.gif")
t2.shape("wonder.gif")
t2.goto(100,-200)
b=t2.stamp()


t2.penup()
turtle.addshape("wonder.gif")
t2.shape("wonder.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)
enter=input("Press enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('pale green')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Sport", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(0,-50)
t.pendown()
t.write("Cross Country", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(60,10)
t.fillcolor('blue')
t.pendown()
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()

t2.penup()
turtle.addshape("running.gif")
t2.shape("running.gif")
t2.goto(100,-200)
a=t2.stamp()


t2.penup()
turtle.addshape("running.gif")
t2.shape("running.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)

enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()